# Generated by Django 4.2.13 on 2025-08-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0043_operation_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerserver',
            name='aap_environment',
            field=models.BooleanField(default=False),
        ),
    ]

